apiVersion: apps/v1
kind: Deployment
metadata:
  name: spock-lizard-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spock-lizard-docker
  template:
    metadata:
      labels:
        app: spock-lizard-docker
    spec:
      containers:
      - name: spock-lizard-docker
        image: rameshkumarverma/spock-lizard-docker:latest 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name:spock-lizard-docker-service
spec:
  selector:
    app: spock-lizard-docker
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
